version: "3"

services:
  web:
    build: .
    hostname: link-preview
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - main_network

networks:
  main_network:
    external: true
